const STORAGE_KEY='wildMageCharacterDraftV1';
const DEFAULT_CHARACTER={skin:'fair',hair:{style:'curlyShort',color:'darkBrown'},eyes:{shape:'mid',color:'brown'},mouth:{style:'thin-smile',color:'none'},features:{freckles:false,beard:false},hat:{style:'hood',color:'green'},clothing:{style:'cloak',color:'green'},hold:'staff'};
let character=loadCharacter();
let active='hair';
const categories=[['skin','●','Skin'],['hair','✦','Hair'],['eyes','◉','Eyes'],['mouth','⌣','Mouth'],['features','✧','Features'],['hat','⌃','Hat'],['clothing','♜','Clothing'],['hold','⌁','Hold']];
const preview=document.getElementById('magePreview');
const tabs=document.getElementById('categoryTabs');
const content=document.getElementById('editorContent');
const savedState=document.getElementById('savedState');
function loadCharacter(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return saved||JSON.parse(JSON.stringify(DEFAULT_CHARACTER))}catch{return JSON.parse(JSON.stringify(DEFAULT_CHARACTER))}}
function saveCharacter(){localStorage.setItem(STORAGE_KEY,JSON.stringify(character));savedState.textContent='Saved locally'}
function render(){ccRenderMage(preview,character);renderTabs();renderEditor()}
function renderTabs(){tabs.innerHTML='';categories.forEach(([key,icon,label])=>{const b=document.createElement('button');b.className='category-tab'+(active===key?' active':'');b.innerHTML='<span>'+icon+'</span>'+label;b.onclick=()=>{active=key;render()};tabs.appendChild(b)})}
function heading(title,copy){content.innerHTML='<div class="section-title"><div><h2>'+title+'</h2><p>'+copy+'</p></div></div>'}
function mountBlock(title,node){const sec=document.createElement('section');sec.className='option-block';const h=document.createElement('h3');h.textContent=title;sec.appendChild(h);sec.appendChild(node);content.appendChild(sec)}
function choiceGrid(kind,items,current){const box=document.createElement('div');box.className='choice-grid';items.forEach(item=>{const key=item[0],label=item[1],group=item[2];const b=document.createElement('button');b.className='choice-card'+(key===current?' selected':'');const thumb=document.createElement('div');thumb.className='thumb';if(kind!=='skin')thumb.appendChild(ccThumb(kind,key,character));b.appendChild(thumb);const text=document.createElement('b');text.textContent=label;b.appendChild(text);if(group){const sm=document.createElement('small');sm.textContent=group;b.appendChild(sm)}b.onclick=()=>{setChoice(kind,key);render()};box.appendChild(b)});return box}
function swatchGrid(palette,current,onPick){const box=document.createElement('div');box.className='swatches';Object.entries(palette).forEach(([key,color])=>{const b=document.createElement('button');b.className='swatch'+(key===current?' selected':'');b.style.setProperty('--c',color);b.innerHTML='<i></i><span>'+pretty(key)+'</span>';b.onclick=()=>{onPick(key);render()};box.appendChild(b)});return box}
function toggle(name,desc,on,fn){const b=document.createElement('button');b.className='toggle-card'+(on?' selected':'');b.innerHTML='<span class="tick"></span><span><strong>'+name+'</strong><small>'+desc+'</small></span>';b.onclick=()=>{fn(!on);render()};return b}
function setChoice(kind,key){if(kind==='hair')character.hair.style=key;if(kind==='eyes')character.eyes.shape=key;if(kind==='mouth')character.mouth.style=key;if(kind==='hat')character.hat.style=key;if(kind==='clothing')character.clothing.style=key;if(kind==='hold')character.hold=key}
function renderEditor(){if(active==='skin')renderSkin();if(active==='hair')renderHair();if(active==='eyes')renderEyes();if(active==='mouth')renderMouth();if(active==='features')renderFeatures();if(active==='hat')renderHat();if(active==='clothing')renderClothing();if(active==='hold')renderHold()}
function renderSkin(){heading('Skin','Choose one of the three approved skin tones.');const items=[['fair','Fair'],['medium','Medium / Brown'],['dark','Dark']];const box=choiceGrid('skin',items,character.skin);[...box.children].forEach((b,i)=>b.onclick=()=>{character.skin=items[i][0];render()});mountBlock('Skin tone',box)}
function renderHair(){heading('Hair','Choose the shape first, then apply one colour.');mountBlock('Hair style',choiceGrid('hair',CC_OPTIONS.hair,character.hair.style));mountBlock('Hair colour',swatchGrid(CC_PALETTES.hair,character.hair.color,k=>character.hair.color=k))}
function renderEyes(){heading('Eyes','Three shapes and six iris colours.');mountBlock('Eye shape',choiceGrid('eyes',CC_OPTIONS.eyes,character.eyes.shape));mountBlock('Eye colour',swatchGrid(CC_PALETTES.eyes,character.eyes.color,k=>character.eyes.color=k))}
function renderMouth(){heading('Mouth','Thin or thick lips with smile, straight or surprised expressions.');mountBlock('Mouth shape',choiceGrid('mouth',CC_OPTIONS.mouth,character.mouth.style));mountBlock('Lip colour',swatchGrid(CC_PALETTES.lips,character.mouth.color,k=>character.mouth.color=k))}
function renderFeatures(){heading('Features','Freckles and beard can be combined. Beard follows hair colour.');const row=document.createElement('div');row.className='toggle-row';row.appendChild(toggle('Freckles','Visible freckles across cheeks and nose',character.features.freckles,v=>character.features.freckles=v));row.appendChild(toggle('Short / trimmed beard','Automatically uses the selected hair colour',character.features.beard,v=>character.features.beard=v));mountBlock('Facial features',row)}
function renderHat(){heading('Hat / Headwear','Hood, witch hat, cap or no headwear.');mountBlock('Headwear',choiceGrid('hat',CC_OPTIONS.hat,character.hat.style));if(character.hat.style!=='none')mountBlock('Hat colour',swatchGrid(CC_PALETTES.cloth,character.hat.color,k=>character.hat.color=k))}
function renderClothing(){heading('Coat / Cloak','Choose the garment and one of the nine approved colours.');mountBlock('Style',choiceGrid('clothing',CC_OPTIONS.clothing,character.clothing.style));mountBlock('Colour',swatchGrid(CC_PALETTES.cloth,character.clothing.color,k=>character.clothing.color=k))}
function renderHold(){heading('Hold / Magic item','Pick the magical item your character carries or channels.');mountBlock('Magic item',choiceGrid('hold',CC_OPTIONS.hold,character.hold))}
function randomize(){const pick=a=>a[Math.floor(Math.random()*a.length)];character={skin:pick(Object.keys(CC_PALETTES.skin)),hair:{style:pick(CC_OPTIONS.hair)[0],color:pick(Object.keys(CC_PALETTES.hair))},eyes:{shape:pick(CC_OPTIONS.eyes)[0],color:pick(Object.keys(CC_PALETTES.eyes))},mouth:{style:pick(CC_OPTIONS.mouth)[0],color:pick(Object.keys(CC_PALETTES.lips))},features:{freckles:Math.random()>.5,beard:Math.random()>.5},hat:{style:pick(CC_OPTIONS.hat)[0],color:pick(Object.keys(CC_PALETTES.cloth))},clothing:{style:pick(CC_OPTIONS.clothing)[0],color:pick(Object.keys(CC_PALETTES.cloth))},hold:pick(CC_OPTIONS.hold)[0]};savedState.textContent='Unsaved changes';render()}
function pretty(k){return k.replace(/([A-Z])/g,' $1').replace(/^./,m=>m.toUpperCase())}
document.getElementById('randomizeBtn').onclick=randomize;
document.getElementById('resetBtn').onclick=()=>{character=JSON.parse(JSON.stringify(DEFAULT_CHARACTER));savedState.textContent='Unsaved changes';render()};
document.getElementById('saveBtn').onclick=saveCharacter;
render();